"""empty message

Revision ID: 6dcbc5cf85e5
Revises: a23ad7597c81
Create Date: 2024-11-12 21:19:36.689475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dcbc5cf85e5'
down_revision = 'a23ad7597c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
