"""empty message

Revision ID: 819f9f2bb08f
Revises: 7f2239cc841f
Create Date: 2024-10-24 11:30:37.332850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819f9f2bb08f'
down_revision = '7f2239cc841f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petgram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_petgram', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petgram', schema=None) as batch_op:
        batch_op.drop_column('categoria_petgram')

    # ### end Alembic commands ###
