"""empty message

Revision ID: 82596d3da284
Revises: 3240fea83455
Create Date: 2024-10-26 16:22:09.227431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82596d3da284'
down_revision = '3240fea83455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petgram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cricao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petgram', schema=None) as batch_op:
        batch_op.drop_column('data_cricao')

    # ### end Alembic commands ###
