"""empty message

Revision ID: ac5173e7b7ef
Revises: 1613bd444312
Create Date: 2024-08-18 21:56:37.999718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5173e7b7ef'
down_revision = '1613bd444312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petgram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_url', sa.String(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('imagem_url')

    with op.batch_alter_table('petgram', schema=None) as batch_op:
        batch_op.drop_column('imagem_url')

    # ### end Alembic commands ###
