from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b730b69689b5'
down_revision = 'c931666812d4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(
            'fk_post_user',  # Nome da chave estrangeira
            'user',  # Tabela referenciada
            ['user_id'],  # Colunas na tabela 'post'
            ['id']  # Colunas na tabela 'user'
        )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_user', type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
